import './globals.scss'
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] })

import Providers from './providers';

export const metadata = {
  title: 'Fenix - Soluções Inteligentes',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={inter.className}>{children}

        <Providers>{children}</Providers>

      </body>
    </html>
  )
}